add Chart.yaml and error messaging

diff --git a/.github/workflows/require-changelog.yaml b/.github/workflows/require-changelog.yaml
--- a/.github/workflows/require-changelog.yaml
+++ b/.github/workflows/require-changelog.yaml
@@ -42,17 +42,38 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
           tag: ${{ matrix.chart }}@${{ steps.changelog_reader.outputs.version }}
 
+      ##### Check if new changelog version entry matches Chart.yaml #####
+
+      - name: Get Chart Version
+        if: steps.changes.outputs.chart == 'true' && steps.tag.outputs.exists == 'false'
+        id: chart
+        run: |
+          VERSION=$(yq '.version' charts/${{ matrix.chart }}/Chart.yaml)
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
+
+          if [ "$VERSION" = "${{ steps.changelog_reader.outputs.version }}" ]; then
+            echo "matches=true" >> $GITHUB_OUTPUT
+          else
+            echo "matches=false" >> $GITHUB_OUTPUT
+            echo "version-line=$(yq '.version | line' charts/${{ matrix.chart }}/Chart.yaml)"
+          fi
+
+      - name: Error if no changes
+        if: steps.chart.outputs.matches == 'false'
+        run: |
+          echo "::error file charts/${{ matrix.chart }}/Chart.yaml,line=${{ steps.chart.output.version-line }}::Chart version does not match to-be-released changelog entry. Please update the chart version before merging this pull request."
+
       ###### Check if Unreleased section has new entry ######
 
       - name: Checkout default branch
-        if: steps.changes.outputs.chart == 'true' && steps.tag.outputs.tag == 'true'
+        if: steps.changes.outputs.chart == 'true' && steps.tag.outputs.exists == 'true'
         uses: actions/checkout@v3
         with:
           ref: ${{ github.event.repository.default_branch }}
           path: default-branch
 
       - name: Get current Unreleased changelog entry
-        if: steps.changes.outputs.chart == 'true' && steps.tag.outputs.tag == 'true'
+        if: steps.changes.outputs.chart == 'true' && steps.tag.outputs.exists == 'true'
         id: current-unreleased
         uses: mindsers/changelog-reader-action@v2
         with:
@@ -61,10 +82,29 @@ jobs:
           version: Unreleased
 
       - name: Get default branch Unreleased changelog entry
-        if: steps.changes.outputs.chart == 'true' && steps.tag.outputs.tag == 'true'
+        if: steps.changes.outputs.chart == 'true' && steps.tag.outputs.exists == 'true'
         id: default-unreleased
         uses: mindsers/changelog-reader-action@v2
         with:
           validation_level: warn
           path: default-branch/charts/${{ matrix.chart }}/CHANGELOG.md
           version: Unreleased
+
+      - name: Check for "Unreleased" Changes
+        if: steps.changes.outputs.chart == 'true' && steps.tag.outputs.exists == 'true'
+        id: unreleased
+        run: |
+          if [ "${{ steps.current-unreleased.outputs.changes }}" = "${{ steps.default-unreleased.outputs.changes }}" ]; then
+            echo "changed=false" >> $GITHUB_OUTPUT
+          else
+            echo "changed=true" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Print error if "Unreleased" is unchanged
+        if: steps.unreleased.outputs.changed == 'true'
+        run: |
+          echo "::error file charts/${{ matrix.chart }}/CHANGELOG.md::Changelog does not include a new version or unreleased entry. Please add an entry before merging this pull request."
+
+      - name: Error if failure
+        if: steps.chart.outputs.matches == 'false' || steps.unreleased.outputs.changed == 'true'
+        run: exit 1
